services:
  licenses:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/licenses:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
    environment:
      - SQLCMDSERVER=${SQL_HOST}
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-Password1234!}
      - SQLCMDDBNAME=master
    
      - SMDB_USERNAME=${SMDB_USERNAME:-someSmDbUser}
      - SMDB_PASSWORD=${SMDB_PASSWORD:-someSmDbPassword!}
      - COMPANY_ADMIN_EMAILADDRESS=${COMPANY_ADMIN_EMAILADDRESS:-evaluation@xmpro.com}
      - COMPANY_ID=${COMPANY_ID:-2}
      - LICENSE_API_URL=${LICENSE_API_URL:-https://fa-xmrlicense-nonprod.azurewebsites.net/api/license}
      - DS_PRODUCT_ID=${DS_PRODUCT_ID:-71435803-967a-e9ac-574c-face863f7ec0}
      - AD_PRODUCT_ID=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
  ad:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/ad:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      addbmigrate:
        condition: service_completed_successfully
      addb:
        condition: service_completed_successfully
    ports:
      - "${AD_PORT:-5202}:8443"
    volumes:
      - ${CERTIFICATES_DIR}/certs:/certs
      - ${CERTIFICATES_DIR}/trustedcerts:/trustedcerts
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/ad.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD:-XMPro@Cert2024!}
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${AD_LOG_LEVEL:-Information}
      - xm__xmpro__appDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__appDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__appDesigner__featureFlags__enableLogging=true
      - xm__xmpro__appDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_SERVER:-https://${SM_HOST:-${SQL_HOST}}/}
      - xm__xmpro__xmidentity__client__baseUrl=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - xm__xmpro__xmidentity__client__id=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - xm__xmpro__xmidentity__client__sharedkey=${AD_PRODUCT_KEY:-f27eeb2d-c557-281c-9d4c-fe44cfb74a97}
      - xm__xmpro__data__connectionString=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=AD;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - xm__xmpro__xmsettings__data__connectionString=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=AD;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
      - xm__xmpro__dataStreamDesigner__server__baseUrl=${DS_BASEURL_SERVER:-https://ds:8443/}
  addbmigrate:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/addbmigrate:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      addb:
        condition: service_completed_successfully
    # extra_hosts:
    #   - "${SQL_HOST}:${WINDOWS_IP:-172.17.0.1}"
    environment:
      - ADDB_CONNECTIONSTRING=${ADDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=AD;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - DS_BASEURL_CLIENT=${DS_BASEURL_CLIENT:-https://localhost:5203/}
  addb:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/addb:${REGISTRY_VERSION:-5.0.0-alpha}
    environment:
      - SQLCMDSERVER=${SQL_HOST}
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-Password1234!}
    
      - ADDB_USERNAME=${ADDB_USERNAME:-someAdDbUser}
      - ADDB_PASSWORD=${ADDB_PASSWORD:-someAdDbPassword!}
  smdbmigrate:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/smdbmigrate:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      smdb:
        condition: service_completed_successfully
    # extra_hosts:
    #   - "${SQL_HOST}:${WINDOWS_IP:-172.17.0.1}"
    environment:
      - SMDB_CONNECTIONSTRING=${SMDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=SM;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - COMPANY_NAME=${COMPANY_NAME:-EvaluationCompany}
      - COMPANY_ADMIN_FIRSTNAME=${COMPANY_ADMIN_FIRSTNAME:-SomeCompanyAdminFirstName}
      - COMPANY_ADMIN_SURNAME=${COMPANY_ADMIN_SURNAME:-SomeCompanyAdminSurname}
      - COMPANY_ADMIN_EMAILADDRESS=${COMPANY_ADMIN_EMAILADDRESS:-evaluation@xmpro.com}
      - COMPANY_ADMIN_USERNAME=${COMPANY_ADMIN_USERNAME:-admin@somecompany.example.com}
      - COMPANY_ADMIN_PASSWORD=${COMPANY_ADMIN_PASSWORD:-Password123!}
      - AD_BASEURL_CLIENT=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - AI_BASEURL_CLIENT=$AI_BASEURL_CLIENT
      - DS_BASEURL_CLIENT=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - XMPRO_NOTEBOOK_BASEURL_CLIENT=$XMPRO_NOTEBOOK_BASEURL_CLIENT
      - AD_PRODUCT_ID=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - AI_PRODUCT_ID=${AI_PRODUCT_ID:-b7be889b-01d3-4bd2-95c6-511017472ec8}
      - DS_PRODUCT_ID=${DS_PRODUCT_ID:-71435803-967a-e9ac-574c-face863f7ec0}
      - SM_PRODUCT_ID=${SM_PRODUCT_ID:-380129dd-6ac3-47fc-a399-234394977680}
      - XMPRO_NOTEBOOK_PRODUCT_ID=${XMPRO_NOTEBOOK_PRODUCT_ID:-c6de3c46-e8ab-4c71-8787-947e6fd2292c}
      - AD_PRODUCT_KEY=${AD_PRODUCT_KEY:-f27eeb2d-c557-281c-9d4c-fe44cfb74a97}
      - AI_PRODUCT_KEY=${AI_PRODUCT_KEY:-87c38802-cafb-cfb1-c966-182f86e09b99}
      - DS_PRODUCT_KEY=${DS_PRODUCT_KEY:-f744911d-e8a6-f8fb-9665-61b185845d6a}
      - XMPRO_NOTEBOOK_PRODUCT_KEY=${XMPRO_NOTEBOOK_PRODUCT_KEY:-0c549103-d30a-c402-4b51-2df9e259043f}
      - AI_PRODUCT_ENABLE=${AI_PRODUCT_ENABLE:-true}
  sh:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/stream-host:${REGISTRY_VERSION:-5.0.0-alpha}
    restart: unless-stopped
    depends_on:
      ds:
        condition: service_healthy
      dsdb:
        condition: service_completed_successfully
    env_file:
      - ${CONFIG_DIR:-${CERTIFICATES_DIR}}/sh-config.env
    volumes:
      - ${CERTIFICATES_DIR}/certs:/certs
      - ${CERTIFICATES_DIR}/trustedcerts:/trustedcerts
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/sh.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD:-XMPro@Cert2024!}
      - xm__consolelogging__minimumlevel__default=${SH_LOG_LEVEL:-Information}
      - xm__xmpro__gateway__id=${SH_ID:-100d5683-9b02-de02-817d-4b663dda40f8}
      - xm__xmpro__gateway__name=${SH_NAME:-jonahf-container}
      - xm__xmpro__gateway__serverurl=${DS_BASEURL_SERVER:-https://ds:8443/}
      - xm__xmpro__gateway__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__gateway__featureflags__enablelegacycore=false
      - xm__xmpro__gateway__featureflags__enablelegacycrypto=false
      - xm__xmpro__XMCryptography__TripleDES__Key=
  ds:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/ds:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      dsdb:
        condition: service_completed_successfully
      dsdbmigrate:
        condition: service_completed_successfully
    ports:
      - "${DS_PORT:-5203}:8443"
    volumes:
      - ${CERTIFICATES_DIR}/certs:/certs
      - ${CERTIFICATES_DIR}/trustedcerts:/trustedcerts
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/ds.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD:-XMPro@Cert2024!}
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${DS_LOG_LEVEL:-Information}
      - xm__xmpro__data__connectionString=${DSDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=DS;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - xm__xmpro__xmsettings__data__connectionString=${DSDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=DS;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
      - xm__xmpro__dataStreamDesigner__streamHostDownloadBaseUrl=https://download.app.xmpro.com/
      - xm__xmpro__dataStreamDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_SERVER:-https://${SM_HOST:-${SQL_HOST}}/}
      - xm__xmpro__xmidentity__client__id=${DS_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - xm__xmpro__xmidentity__client__baseUrl=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - xm__xmpro__xmidentity__client__sharedkey=${DS_PRODUCT_KEY:-f744911d-e8a6-f8fb-9665-61b185845d6a}
      - xm__xmpro__keyVault__provider=
      - xm__xmpro__keyVault__name=
      - xm__xmpro__appDesigner__server__baseUrl=${AD_BASEURL_SERVER:-https://ad:8443/}
  dsdb:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/dsdb:${REGISTRY_VERSION:-5.0.0-alpha}
    environment:
      - SQLCMDSERVER=${SQL_HOST}
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-Password1234!}
    
      - DSDB_USERNAME=${DSDB_USERNAME:-someDsDbUser}
      - DSDB_PASSWORD=${DSDB_PASSWORD:-someDsDbPassword!}
  dsdbmigrate:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/dsdbmigrate:${REGISTRY_VERSION:-5.0.0-alpha}
    depends_on:
      dsdb:
        condition: service_completed_successfully
    # extra_hosts:
    #   - "${SQL_HOST}:${WINDOWS_IP:-172.17.0.1}"
    environment:
      - DSDB_CONNECTIONSTRING=${DSDB_CONNECTIONSTRING:-Encrypt=false;Server=tcp:${SQL_HOST};Database=DS;User=sa;Password=${DB_SA_PASSWORD:-Password1234!}}
  smdb:
    image: ${REGISTRY_URL:-xmpro.azurecr.io}/smdb:${REGISTRY_VERSION:-5.0.0-alpha}
    environment:
      - SQLCMDSERVER=${SQL_HOST}
      - SQLCMDUSER=sa
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-Password1234!}
    
      - SMDB_USERNAME=${SMDB_USERNAME:-someSmDbUser}
      - SMDB_PASSWORD=${SMDB_PASSWORD:-someSmDbPassword!}
