services:
  smdbmigrate:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/smdbmigrate:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdb:
        condition: service_completed_successfully
    environment:
      - SMDB_CONNECTIONSTRING=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=SM;User=${SMDB_USER:-someSmDbUser};Password=${SMDB_PASSWORD:-someSmDbPassword!}
      - COMPANY_NAME=${COMPANY_NAME:-Evaluation}
      - COMPANY_ADMIN_FIRSTNAME=${COMPANY_ADMIN_FIRSTNAME:-SomeCompanyAdminFirstName}
      - COMPANY_ADMIN_SURNAME=${COMPANY_ADMIN_SURNAME:-SomeCompanyAdminSurname}
      - COMPANY_ADMIN_EMAILADDRESS=${COMPANY_ADMIN_EMAILADDRESS:-evaluation@xmpro.com}
      - COMPANY_ADMIN_USERNAME=${COMPANY_ADMIN_USERNAME:-admin@somecompany.example.com}
      - COMPANY_ADMIN_PASSWORD=${COMPANY_ADMIN_PASSWORD:-EBhxyO9Po=$COMPANY_ADMIN_PASSWORDd}
      - SITE_ADMIN_PASSWORD=${SITE_ADMIN_PASSWORD:-T$q8[K:+?]v7}
      - AD_BASEURL_CLIENT=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - AI_BASEURL_CLIENT=${AI_BASEURL_CLIENT:-https://localhost:5204/}
      - DS_BASEURL_CLIENT=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - XMPRO_NOTEBOOK_BASEURL_CLIENT=$XMPRO_NOTEBOOK_BASEURL_CLIENT
      - AD_PRODUCT_ID=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - AI_PRODUCT_ID=${AI_PRODUCT_ID:-b7be889b-01d3-4bd2-95c6-511017472ec8}
      - DS_PRODUCT_ID=${DS_PRODUCT_ID:-71435803-967a-e9ac-574c-face863f7ec0}
      - SM_PRODUCT_ID=${SM_PRODUCT_ID:-380129dd-6ac3-47fc-a399-234394977680}
      - XMPRO_NOTEBOOK_PRODUCT_ID=${XMPRO_NOTEBOOK_PRODUCT_ID:-c6de3c46-e8ab-4c71-8787-947e6fd2292c}
      - AD_PRODUCT_KEY=${AD_PRODUCT_KEY:-4d2d4ea9-2144-0d0f-50a6-e0067b224100}
      - AI_PRODUCT_KEY=${AI_PRODUCT_KEY:-c8638c1a-1df2-994f-7ae1-d1726d7c1c1e}
      - DS_PRODUCT_KEY=${DS_PRODUCT_KEY:-d7ef9ecb-3309-6316-1ab8-8f2f38417f65}
      - XMPRO_NOTEBOOK_PRODUCT_KEY=${XMPRO_NOTEBOOK_PRODUCT_KEY:-21c3e2f8-c96e-23b7-09de-4c50f06b3e8a}
      - AI_PRODUCT_ENABLE=${AI_PRODUCT_ENABLE:-true}
  licenses:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/licenses:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
      smdb:
        condition: service_completed_successfully
    environment:
      - SQLCMDSERVER=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433}
      - SQLCMDENCRYPT=${DB_ENCRYPT:-true}
      - SQLCMDTRUSTSERVERCERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE:-true}
      - SQLCMDUSER=${DB_SA_USER:-}
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-}
      - SQLCMDDBNAME=master
    
      - SMDB_USER=${SMDB_USER:-someSmDbUser}
      - SMDB_PASSWORD=${SMDB_PASSWORD:-someSmDbPassword!}
      - COMPANY_ADMIN_EMAILADDRESS=${COMPANY_ADMIN_EMAILADDRESS:-evaluation@xmpro.com}
      - COMPANY_ID=${COMPANY_ID:-2}
      - LICENSE_API_URL=${LICENSE_API_URL:-https://licensesnp.xmpro.com/api/license}
      - DS_PRODUCT_ID=${DS_PRODUCT_ID:-71435803-967a-e9ac-574c-face863f7ec0}
      - AD_PRODUCT_ID=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - AI_PRODUCT_ID=${AI_PRODUCT_ID:-b7be889b-01d3-4bd2-95c6-511017472ec8}
  ad:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/ad:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
      licenses:
        condition: service_completed_successfully
      addbmigrate:
        condition: service_completed_successfully
      addb:
        condition: service_completed_successfully
    ports:
      - "${AD_PORT:-5202}:8443"
    restart: unless-stopped
    environment:
      - AD_SSL_CERT=${AD_SSL_CERT:-}
      - AD_SSL_CERT_PASSWORD=${AD_SSL_CERT_PASSWORD:-}
      - SM_SSL_CERT_TRUST=${SM_SSL_CERT_TRUST:-}
      - DS_SSL_CERT_TRUST=${DS_SSL_CERT_TRUST:-}
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${AD_LOG_LEVEL:-Information}
      - xm__xmpro__appDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__appDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__appDesigner__featureFlags__enableLogging=true
      - xm__xmpro__appDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_CLIENT:-https://localhost:5200/}
      - xm__xmpro__xmidentity__server__internalBaseUrl=${SM_BASEURL_SERVER:-https://host.docker.internal:5200/}
      - xm__xmpro__xmidentity__client__baseUrl=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - xm__xmpro__xmidentity__client__id=${AD_PRODUCT_ID:-fe011f90-5bb6-80ad-b0a2-56300bf3b65d}
      - xm__xmpro__xmidentity__client__sharedkey=${AD_PRODUCT_KEY:-4d2d4ea9-2144-0d0f-50a6-e0067b224100}
      - xm__xmpro__dataStreamDesigner__server__baseUrl=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - xm__xmpro__dataStreamDesigner__server__internalBaseUrl=${DS_BASEURL_SERVER:-https://ds:8443/}
      - xm__xmpro__appDesigner__server__baseUrl=${AD_BASEURL_SERVER:-https://ad:8443/}
      - xm__xmpro__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AD;User=${ADDB_USER:-someAdDbUser};Password=${ADDB_PASSWORD:-someAdDbPassword!}
      - xm__xmpro__xmsettings__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AD;User=${ADDB_USER:-someAdDbUser};Password=${ADDB_PASSWORD:-someAdDbPassword!}
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
    volumes:
      - ${CERTIFICATES_DIR:-./certs}/certs:/certs
      - ${CERTIFICATES_DIR:-./certs}/trustedcerts:/trustedcerts
  ds:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/ds:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
      licenses:
        condition: service_completed_successfully
      dsdbmigrate:
        condition: service_completed_successfully
      dsdb:
        condition: service_completed_successfully
    ports:
      - "${DS_PORT:-5203}:8443"
    restart: unless-stopped
    environment:
      - DS_SSL_CERT=${DS_SSL_CERT:-}
      - DS_SSL_CERT_PASSWORD=${DS_SSL_CERT_PASSWORD:-}
      - SM_SSL_CERT_TRUST=${SM_SSL_CERT_TRUST:-}
      - AD_SSL_CERT_TRUST=${AD_SSL_CERT_TRUST:-}
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${DS_LOG_LEVEL:-Information}
      - xm__xmpro__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=DS;User=${DSDB_USER:-someDsDbUser};Password=${DSDB_PASSWORD:-someDsDbPassword!}
      - xm__xmpro__xmsettings__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=DS;User=${DSDB_USER:-someDsDbUser};Password=${DSDB_PASSWORD:-someDsDbPassword!}
      - xm__xmpro__dataStreamDesigner__streamHostDownloadBaseUrl=https://download.app.xmpro.com/
      - xm__xmpro__dataStreamDesigner__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableHealthChecks=false
      - xm__xmpro__dataStreamDesigner__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_CLIENT:-https://localhost:5200/}
      - xm__xmpro__xmidentity__server__internalBaseUrl=${SM_BASEURL_SERVER:-https://host.docker.internal:5200/}
      - xm__xmpro__xmidentity__client__id=${DS_PRODUCT_ID:-71435803-967a-e9ac-574c-face863f7ec0}
      - xm__xmpro__xmidentity__client__baseUrl=${DS_BASEURL_CLIENT:-https://localhost:5203/}
      - xm__xmpro__xmidentity__client__sharedkey=${DS_PRODUCT_KEY:-d7ef9ecb-3309-6316-1ab8-8f2f38417f65}
      - xm__xmpro__appDesigner__server__baseUrl=${AD_BASEURL_CLIENT:-https://localhost:5202/}
      - xm__xmpro__appDesigner__server__internalBaseUrl=${AD_BASEURL_SERVER:-https://ad:8443/}
    volumes:
      - ${CERTIFICATES_DIR:-./certs}/certs:/certs
      - ${CERTIFICATES_DIR:-./certs}/trustedcerts:/trustedcerts
  ai:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/ai:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
      licenses:
        condition: service_completed_successfully
      aidb:
        condition: service_completed_successfully
      aidbmigrate:
        condition: service_completed_successfully
    ports:
      - "${AI_PORT:-5204}:8443"
    restart: unless-stopped
    environment:
      - AI_SSL_CERT=${AI_SSL_CERT:-}
      - AI_SSL_CERT_PASSWORD=${AI_SSL_CERT_PASSWORD:-}
      - SM_SSL_CERT_TRUST=${SM_SSL_CERT_TRUST:-}
      - ASPNETCORE_ENVIRONMENT=dev
      - xm__serilog__minimumlevel__default=${AI_LOG_LEVEL:-Information}
      - xm__xmpro__ai__featureFlags__dbMigrationsEnabled=false
      - xm__xmpro__ai__featureFlags__enableHealthChecks=false
      - xm__xmpro__ai__featureFlags__enableLogging=true
      - xm__xmpro__ai__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__xmidentity__server__baseUrl=${SM_BASEURL_CLIENT:-https://localhost:5200/}
      - xm__xmpro__xmidentity__server__internalBaseUrl=${SM_BASEURL_SERVER:-https://host.docker.internal:5200/}
      - xm__xmpro__xmidentity__client__baseUrl=${AI_BASEURL_CLIENT:-https://localhost:5204/}
      - xm__xmpro__xmidentity__client__id=${AI_PRODUCT_ID:-b7be889b-01d3-4bd2-95c6-511017472ec8}
      - xm__xmpro__xmidentity__client__sharedkey=${AI_PRODUCT_KEY:-c8638c1a-1df2-994f-7ae1-d1726d7c1c1e}
      - xm__xmpro__ai__server__baseUrl=${AI_BASEURL_SERVER:-https://ai:8443/}
      - xm__xmpro__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AI;User=${AIDB_USER:-someAiDbUser};Password=${AIDB_PASSWORD:-someAiDbPassword!}
      - xm__xmpro__xmsettings__data__connectionString=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AI;User=${AIDB_USER:-someAiDbUser};Password=${AIDB_PASSWORD:-someAiDbPassword!}
      - xm__xmpro__healthChecks__cssPath=ClientApp/src/assets/content/styles/healthui.css
    volumes:
      - ${CERTIFICATES_DIR:-./certs}/certs:/certs
      - ${CERTIFICATES_DIR:-./certs}/trustedcerts:/trustedcerts
  addbmigrate:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/addbmigrate:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      addb:
        condition: service_completed_successfully
    environment:
      - ADDB_CONNECTIONSTRING=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AD;User=${ADDB_USER:-someAdDbUser};Password=${ADDB_PASSWORD:-someAdDbPassword!}
      - DS_BASEURL_CLIENT=${DS_BASEURL_CLIENT:-https://localhost:5203/}
  dsdbmigrate:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/dsdbmigrate:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      dsdb:
        condition: service_completed_successfully
    environment:
      - DSDB_CONNECTIONSTRING=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=DS;User=${DSDB_USER:-someDsDbUser};Password=${DSDB_PASSWORD:-someDsDbPassword!}
      - DSDB_COLLECTION_ID=${DSDB_COLLECTION_ID:-c55f1a3e-90e4-45b0-9326-780dda46e66b}
      - DSDB_COLLECTION_SECRET=${DSDB_COLLECTION_SECRET:-dPdmDOFHNPAErSXjDHYwylB5myK08xbr}
      - DSDB_COLLECTION_NAME=${DSDB_COLLECTION_NAME:-COLLECTION 5.0.0-alpha}
  aidb:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/aidb:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    environment:
      - SQLCMDSERVER=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433}
      - SQLCMDENCRYPT=${DB_ENCRYPT:-true}
      - SQLCMDTRUSTSERVERCERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE:-true}
      - SQLCMDUSER=${DB_SA_USER:-}
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-}
    
      - AIDB_USER=${AIDB_USER:-someAiDbUser}
      - AIDB_PASSWORD=${AIDB_PASSWORD:-someAiDbPassword!}
  aidbmigrate:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/aidbmigrate:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      aidb:
        condition: service_completed_successfully
    environment:
      - AIDB_CONNECTIONSTRING=Server=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433};Encrypt=${DB_ENCRYPT:-true};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE:-true};PersistSecurityInfo=${DB_PERSIST_SECURITY_INFO:-false};Database=AI;User=${AIDB_USER:-someAiDbUser};Password=${AIDB_PASSWORD:-someAiDbPassword!}
  addb:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/addb:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    environment:
      - SQLCMDSERVER=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433}
      - SQLCMDENCRYPT=${DB_ENCRYPT:-true}
      - SQLCMDTRUSTSERVERCERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE:-true}
      - SQLCMDUSER=${DB_SA_USER:-}
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-}
    
      - ADDB_USER=${ADDB_USER:-someAdDbUser}
      - ADDB_PASSWORD=${ADDB_PASSWORD:-someAdDbPassword!}
  sh:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/stream-host:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    depends_on:
      smdbmigrate:
        condition: service_completed_successfully
      licenses:
        condition: service_completed_successfully
      ds:
        condition: service_healthy
      dsdb:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      - DS_SSL_CERT_TRUST=${DS_SSL_CERT_TRUST:-}
      - xm__consolelogging__minimumlevel__default=${SH_LOG_LEVEL:-Information}
      - xm__xmpro__gateway__id=${SH_ID:-b7216b34-87ed-3515-bbce-6df6dd4d50ff}
      - xm__xmpro__gateway__name=${SH_NAME:-vsts-container}
      - xm__xmpro__gateway__serverurl=${DS_BASEURL_SERVER:-https://ds:8443/}
      - xm__xmpro__gateway__collectionid=${DSDB_COLLECTION_ID:-c55f1a3e-90e4-45b0-9326-780dda46e66b}
      - xm__xmpro__gateway__secret=${DSDB_COLLECTION_SECRET:-dPdmDOFHNPAErSXjDHYwylB5myK08xbr}
      - xm__xmpro__gateway__featureFlags__enableApplicationInsightsTelemetry=false
      - xm__xmpro__gateway__featureflags__enablelegacycore=false
      - xm__xmpro__gateway__featureflags__enablelegacycrypto=false
      - xm__xmpro__XMCryptography__TripleDES__Key=
    volumes:
      - ${CERTIFICATES_DIR:-./certs}/certs:/certs
      - ${CERTIFICATES_DIR:-./certs}/trustedcerts:/trustedcerts
  smdb:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/smdb:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    environment:
      - SQLCMDSERVER=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433}
      - SQLCMDENCRYPT=${DB_ENCRYPT:-true}
      - SQLCMDTRUSTSERVERCERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE:-true}
      - SQLCMDUSER=${DB_SA_USER:-}
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-}
    
      - SMDB_USER=${SMDB_USER:-someSmDbUser}
      - SMDB_PASSWORD=${SMDB_PASSWORD:-someSmDbPassword!}
  dsdb:
    image: ${REGISTRY_URL:-xmprononprod.azurecr.io}/dsdb:${REGISTRY_VERSION:-5.0.0.34-alpha-0020ccb984}
    environment:
      - SQLCMDSERVER=${DB_PROTOCOL:-tcp}:${DB_SERVER_INCONTAINERS:-host.docker.internal},${DB_PORT_INCONTAINERS:-1433}
      - SQLCMDENCRYPT=${DB_ENCRYPT:-true}
      - SQLCMDTRUSTSERVERCERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE:-true}
      - SQLCMDUSER=${DB_SA_USER:-}
      - SQLCMDPASSWORD=${DB_SA_PASSWORD:-}
    
      - DSDB_USER=${DSDB_USER:-someDsDbUser}
      - DSDB_PASSWORD=${DSDB_PASSWORD:-someDsDbPassword!}
